# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    exclude:
      - main
  paths:
    include:
      - api

pr:
  branches:
    include:
      - main
  paths:
    include:
      - api
      - webapp
      - Dockerfile
      - docs
      
pool:
  name: Local

variables: 
    imageTag: $(Build.BuildId)$(date +"%d%m%Y")

stages:
  - stage: build
    jobs:
      # Instala o flake8 e executa análise de lint no diretório ./api
      - job: Flake8
        displayName: 'Análise flake8'
        steps:
          - script: |
              python3 -m venv venv
              source venv/bin/activate
              python -m pip install flake8
              flake8 ./api
            displayName: 'Run Python lint'
            continueOnError: "true"
              
  - stage: deploy
    dependsOn: 
      - build
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main'))
    jobs:
      # preparar deploy local e realizar testes locais
      - job: Testeslocais
        displayName: 'Preparar e realizar testes locais'
        steps:
          - script: |
              python3 -m venv venv
              source venv/bin/activate
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install schemathesis
              python manage.py migrate
            displayName: 'Create and activate venv + Install prerequisites and test tool'
          - script: |
              source venv/bin/activate
              python manage.py runserver &
              sleep 5
            displayName: 'Start server'
          - script: |
              RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:8000/api/produto)
              if [[ "$RESPONSE" -ge 200 && "$RESPONSE" -lt 300 ]]; then
                echo "Request succeeded with status code $RESPONSE."
              else
                echo "Request failed with status code $RESPONSE."
                exit 1
              fi
            displayName: 'Acceptance test'
            continueOnError: "false"
          - script: 
              source venv/bin/activate
              schemathesis run --base-url=http://localhost:8000/api docs/clogistica.yml \
                --checks=all \
                --validate-schema=true \
                --hypothesis-max-examples=5 \
                --junit-xml=schemathesis-results.xml
            displayName: 'Run API contract tests'
          # Publish test results
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '*-results.xml'
              testRunTitle: 'API Test Results'
            condition: succeededOrFailed()
      # Build da docker image
      - job: dockerbuild
        displayName: 'Build docker image'
        dependsOn: Testeslocais
        variables: 
        - group: g3vars
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '28.0.4'

          - script: |
              docker login AzureHubG3.azurecr.io -u $(AzureHubG3user) -p $(AzureHubG3pass)
            displayName: 'Login to container registry'
            env:
              ACR_USERNAME: $(AzureHubG3user)
              ACR_PASSWORD: $(AzureHubG3pass)
        # Build the image
          - script: |
              echo "Building timestamp: $(date +"%d%m%Y")"
              docker build -t AzureHubG3.azurecr.io/api:$(imageTag) -f ./Dockerfile .
              docker push AzureHubG3.azurecr.io/api:$(imageTag)
            displayName: 'Build and save Docker image'


