apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-webapp
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"           # Tells Prometheus to scrape this app
        prometheus.io/port: "80"               # The port where metrics are exposed (should match containerPort)
        prometheus.io/path: "/p/metrics"         # The path where metrics are exposed
    spec:
      containers:
      - name: api-webapp
        image: azurehubg3.azurecr.io/api:20052025
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: regcred
