apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 80